services:
  frostfire-assets-dev:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile.dev
    container_name: frostfire-assets-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../../.env.development
    networks:
      - frostfire-network-dev

networks:
  frostfire-network-dev:
    driver: bridge
