services:
  frostfire-assets-prod:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile.prod
    container_name: frostfire-assets-prod
    restart: always
    network_mode: "host"
    env_file:
      - ../../.env.production